- bintray.sh
This was why AppRun was not being uploaded, but AppImages were
> Fix name extraction for non AppImages

- bintray.sh
Checks swapped in order to keep bintray.sh from breaking PR Travis builds on all the repos that use this script
As noted by @shoogle in https://github.com/probonopd/AppImageKit/pull/118#issuecomment-196262402
> Keep bintray.sh from breaking PR Travis builds

- bintray-tidy.sh
- bintray.sh
MuseScore's nightly repo on Bintray was suspended due to the number of packages we were uploading. I wrote this script to delete old versions automatically when uploading a new AppImage. There are different ways it can be used, see the showHelp function.
> Delete older versions from Bintray.

- recipes/chromium/Recipe
Disable the file-based sandbox only. This way the kernel level sandboxing still takes effect for security.
> Don't turn off the sandbox.

- recipes/thunderbird/Recipe
Thunderbird Recipe, mostly copied from the firefox one.
Runs on Ubuntu 16.04, 12,04 (where it was built), Centos7, Debian stable.
Like Firefox, it won't run on Centos6 because of the glibc version
> Add Thunderbird Recipe

- recipes/firefox-dev/Recipe
Works with the same glibc version firefox needs (so no Centos6)
The issue is that I can't get the .desktop file to have the correct name.
It is possible to change something in the desktopintegration script?
It would need to change the name from appimagekit-firefox.desktop to appimagekit-firefox-dev.desktop;
and the "Name" to Firefox Developer"
> Add Firefox Developer Recipe

- recipes/texworks/Recipe
Don't merge yet.
Has issues with localization and themes
It's a qt based ui for TeX. It works, but I have an issue with the theme and the locale
(I have an Italian keyboard layout, and it seems to pick that for the ui, even though the system language is english)
```
QGtkStyle was unable to detect the current GTK+ theme.
Qt: Cannot set locale modifiers: 
```
Do I need some other libraries for that? (the locale is fixed if I set LC_ALL=$LANG before I run the AppImage, LANG being en_US.UTF-8)
> Add TeXworks Recipe

- recipes/firefox/Recipe
To get the dialog asking to install the .desktop file I had to fox the following (like discussed in the firefox-dev PR):
Fix firefox.desktop (add Type=Application), or the .desktop is not parsable
Set AppRun to firefox.wrapper to invoke the correct executable
> Fix desktop integration in Firefox Recipe

- recipes/firefox-dev/Recipe
Renamed to Aurora and removed the desktopintegration.
It would be nice to fix that, but for now this works
> Add Firefox Developer (Aurora) Recipe

- recipes/chromium/Recipe
https://bugs.chromium.org/p/chromium/issues/detail?id=598454
Initial work has started on fixing the check. Working correctly in the current nightlies so the next stable branch that gets built should have no need for this flag.
> Remove disabling the setuid sandbox

- recipes/meta/Firefox.yml
I tried to add a Firefox yml to test the new system.
From the extracted tarfile there's one file missing, `libnss3.so`.
This file is in the archive, so I assume it's removed somewhere in the Recipe file (could this be?)
> Add Firefox yml

- recipes/scribus/Dockerfile
This works because Docker Hub not only imports the Dockerfile from GitHub, it also imports everything in the directory which contains the Dockerfile (including sub-directories). The advantage is that if I make changes to the Recipe in my fork, and I set up Docker on my fork, then my Docker will use my Recipe instead of yours.
> Use local copy of Recipe

- recipes/meta/Recipe
The order is not guaranteed to be sorted in any way.
See http://serverfault.com/a/181815
Fixes https://github.com/probonopd/AppImages/issues/163
> Sort the result of `find` before taking the first line

- functions.sh
`strings` checks the whole file, readelf only the symbol table. The result may be incorrect if `strings` finds a line with `GLIBC_2` somewhere else in the file (even if this is very unlikely). Also `uniq` is not needed here.
> use readelf to find out glibc dependency

- recipes/subsurface/Dockerfile
- recipes/subsurface/Recipe
This way things get cached by Docker and you don't have to wait as long as you
run things (still takes forever, but not QUITE as long). This of course only
works when running the process on the same system - doesn't help on Travis.
Signed-off-by: Dirk Hohndel <dirk@hohndel.org>
> Install the packages in the Dockerfile instead of the Recipe

- functions.sh
Modification to `copy_deps` so that dynamics-links already pointing inside the "current directory" will be skipped.
This prevent coping libraries already bundled in some "special" case, for example when using the `pip` distribution of `PyQt5` that comes already bundled with a compiled version of Qt
> Update copy_deps to skip "static" links

- functions.sh
As discovered in TheAssassin/redeclipse-appimage#3, `delete_blacklisted` does
not delete symlinks to the real `*.so` files. This can cause issues when
an AppImage wants to use the precompiled libraries from a distribution like
Debian which uses symlinks to point to a specific version of a library.
This commit fixes `delete_blacklisted`'s behavior to delete such symlinks.
It is subject to further discussions whether to make the filenames in
`excludelist` wildcards to delete both the symlinks and the files they point
to.
Another approach would be using `readlink -f` to properly resolve the symlinks
and delete their targets. This way one does not have to trust on a wildcard,
although it is very unlike that the globs would delete anything but related
shared object files.
> Make delete_blacklisted delete symlinks

- functions.sh
mkdir's exit code won't be 0 if the directory already exists, regardless of
whether -p parameter is used or not.
When a build script calls `set -e` at the beginning to automatically stop a
build when a command fails, the generate_* helpers will fail due to mkdir
being likely to fail. This commit makes sure the exit code is ignored for
the mkdir calls.
> Allow running generate_* with set -e

- recipes/meta/Recipe
This PR attempts to remove the need for a local package repository in order to be able to download the dependencies of meta recipes. Instead of using `dpkg-scanpackages` to create an old-style Debian repository, it uses `dpkg -I` to inspect the `.deb`s and adds these to the list of packages downloaded using `apt-get install --print-uris`.
> Get rid of dpkg-scanpackages

- functions.sh
- recipes/meta/Recipe
This PR:
* includes a small fix with a variable substitution in the meta recipe
* makes the `generate*appimage` helpers automatically include the glibc version in the resulting filename
* drastically increases `.deb` download speed
> More improvements

- functions.sh
- recipes/meta/Recipe
This PR obsoletes all the custom `sed` commands that try to fix the missing trailing semicolons in desktop files by having the recipe automatically insert these if necessary.
Also removes some trailing whitespace.
> Fix missing trailing semicolons in desktop files automatically

- recipes/meta/CAMotics.yml
- recipes/meta/LibreCAD-daily.yml
- recipes/meta/LibreCAD.yml
- recipes/meta/Mpv.yml
- recipes/meta/RedEclipse.yml
Due to the fix committed in 041d232, these commands are no longer necessary, and can be removed safely.
> Remove obsolete sed command

- recipes/meta/php5.6.yml
- recipes/meta/php7.1.yml
This commit adds a few recipes that build AppImages for several versions of the PHP CLI.
The AppImages contain all the PHP extensions that can be built from the Debian PHP source packages.
> Add recipes for multiple versions of the PHP CLI

- functions.sh
Reverts probonopd/AppImages#216, broke the build with `./functions.sh: line 174: 2.3.4: command not found`
> Revert "Include glibc version in AppImage filenames"

- functions.sh
Trying to use `/bin/sh` to run functions.sh causes this error to be displayed:
> build/appimage_functions.sh: 242: build/appimage_functions.sh: Syntax error: "(" unexpected
This appears to be because the `patch_strings_in_file` function is declared with the "function" keyword. None of the other functions in the file use that declaration style and removing the word "function" from the declaration fixes it.
> Fix functions.sh for /bin/sh on Ubuntu Trusty

- functions.sh
Otherwise a comment on the same line as a library name will not be removed.
And empty line don't need to be removed explicitly, the shell will automatically handle that.
> delete_blacklisted(): remove all text after '#'

- recipes/meta/FreeCAD-nightly.yml
Currently AppImage build procedure fails with freecad-daily-daily{.png,.svg,.svgz,.xpm} not present but defined in desktop file. Using default icon name should fix the issue.
https://forum.freecadweb.org/viewtopic.php?f=4&t=22606
> Use default icon name

- recipes/meta/Bluefish.yml
- recipes/meta/Devhelp.yml
- recipes/meta/Go-For-It.yml
- recipes/meta/Mumble.yml
- recipes/meta/PSPP.yml
- recipes/meta/QCTools.yml
- recipes/meta/Synergy.yml
- recipes/meta/X2GoClient.yml
- recipes/meta/XaraLX.yml
- recipes/meta/XnViewMP.yml
- recipes/meta/php5.6.yml
- recipes/meta/php7.1.yml
According to https://wiki.ubuntu.com/Releases, precise is reaching íts end of life on April 28, 2017.
I figured we should move the AppImages now to make sure the AppImage builds work with trusty as well as with precise.
> Switch to trusty as precise is going to be EOL in a few days

- functions.sh
Now if i.e. `libz.so.1` is on the list `libz.so.1.2.8` will be deleted too.
Works for me:
```
+ for FILE in '$BLACKLISTED_FILES'
++ find . -xtype f -regextype egrep -regex '^.*/libz.so.1($|[\.0-9]+$)'
+ FOUND='./lib/x86_64-linux-gnu/libz.so.1.2.8
./lib/x86_64-linux-gnu/libz.so.1'
+ for FILE in '$FOUND'
+ echo 'Deleting blacklisted ./lib/x86_64-linux-gnu/libz.so.1.2.8'
Deleting blacklisted ./lib/x86_64-linux-gnu/libz.so.1.2.8
+ rm -f ./lib/x86_64-linux-gnu/libz.so.1.2.8
+ for FILE in '$FOUND'
+ echo 'Deleting blacklisted ./lib/x86_64-linux-gnu/libz.so.1'
Deleting blacklisted ./lib/x86_64-linux-gnu/libz.so.1
+ rm -f ./lib/x86_64-linux-gnu/libz.so.1
```
> Improve removal of excluded files

- functions.sh
This makes it easier to customize the AppImage according to https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6
Here's an example YAML file that would benefit from this:
``` yaml
app: Aegisub
ingredients:
packages:
#- aegisub-l10n  # localisation doesn't work
dist: stable
sources:
- deb http://ftp.debian.org/debian/ stable main universe
script:
- DEB=libstdc++6_6.3.0-18_amd64.deb
- wget -O ../$DEB -c http://ftp.debian.org/debian/pool/main/g/gcc-6/$DEB
- dpkg-deb -x ../$DEB .
- mkdir -p ./usr/optional/libstdc++
- mv ./usr/lib/x86_64-linux-gnu/libstdc++.so.6* ./usr/optional/libstdc++
- find ./usr -name libstdc++.so.6*-gdb.py -delete
- rm -rf ./AppRun ./usr/lib/x86_64-linux-gnu/x264-10bit
- wget -O AppRun https://github.com/darealshinji/AppImageKit-checkrt/releases/down …
```
> Ignore blacklisted files in ./usr/optional/

- functions.sh
functions.sh script has hardcoded "x86_64" references to AppImage tools making it fail on 32-bit systems.
The following changes will detect system architecture to know which binary version of appimagetool or AppImageAssistant should be used.
Detection method handles all possible Linux name variations
x86-64 architecture: x86_64, amd64
x86 architecture: i386, i486, i586, i686
Changes make it also easy to add ARM architecture support.
> Make functions.sh script usable on non x86-64 systems

- functions.sh
on debian, uname -i returns unknow, then use:  uname -m
as says [man uname](https://www.gnu.org/software/coreutils/manual/html_node/uname-invocation.html#uname-invocation), uname -i is not portable
on debian, on 32 or 64bits architecture,  I can't make an image.
I have fixed with this, and it work.
cordially
> fix for architecture on debian platform

- recipes/meta/FirefoxDeveloperEdition.yml
Upstream had changed the path at which the linux tarball resided, this updates the recipe accordingly.
> Update Firefox dev edition upstream URL

- recipes/meta/FreeCAD-nightly.yml
Due to freecad-daily.desktop file not passing validation daily FreeCAD Travis builds are failing. ATM there doesn't seem to be much interest from PPA maintainers to make the freecad-daily.desktop file pass validation.
Until that happens (likely at the next FreeCAD release) freecad-daily.desktop file passing validation can be created directly. As a result daily FreeCAD Travis builds will be available to end users again.
> Temporary fix .desktop file not passing validation

- recipes/meta/CodeBlocks.yml
Now the recipe uses the oficial Code::Blocks PPA for Ubuntu Precise which is older than the previous recibe version using Debian jessie.
Also install codeblocks-contrib plugins and change the Desktop file so the generated AppImage file doesn't contain "::" in the name, which causes LD_LIBRARY_PATH to go nuts.
Fixes #279
> Change the recipe to use Ubuntu Precise and Code::Blocks PPA

- recipes/meta/Nightingale.yml
Also removed `$*` so that NG doesn't try to open `%U` as a website.
> Nightingale: fix .desktop file

- recipes/meta/Meshmixer.yml
@probonopd Please take a look.
I had a sed expression that handled the double line, working on my other workstation, but not here, so I've just brutally trimmed the text.
Fixes #166.
> recipes/meta: fix meshmixer.desktop

- functions.sh
This PR resolves #549.
This patch allows you to add arbitrary parameters to `generate_type2_appimage` which will be passed on to `appimagetool`.
I also added a feature that you can set the environment variable `NO_GLIBC_VERSION` to create AppImages without the glibc version in the filename.
> Allow overriding of appimagetool parameters

- functions.sh
On my AMD FX6300 workstation:
$ uname -i
AuthenticAMD
This causes functions.sh to fail with ``unsupported``.
> fail to -m for AuthenticAMD

- pkg2appimage
- recipes/FreeCAD-asm3.yml
post_script gives the recipe a chance to modify the downloaded packages from ingredient before installation.
One common use case is for a user to build an AppImage based on a custom-built package from the official source. The recipe can rely on apt to pull dependency from the official source. Once all packages are downloaded, the recipe can use post_script to replace the official package with the custom-built one.
An example recipe FreeCAD-asm3 is included.
> Add post_script section to ingrediants

- recipes/FreeCAD-nightly.yml
Lapack and libblas is not in the correct path for Numpy to find them.
See discussion here: https://forum.freecadweb.org/viewtopic.php?f=4&t=25942
This solution is borrowed from the Octave.yml Receipe.
https://github.com/AppImage/AppImages/blob/master/recipes/Octave.yml
Is this the preferred solution to this problem from AppImage perspective or do you recommend something else?
> Move lapack and libblas to the correct path

- appdir-lint.sh
Due to missing space in `appdir-lin.sh`, it was not running `appstreamcli`.
> Add missing space

- functions.sh
``GenuineIntel`` is also an indicator that ``uname -i`` doesn't return the desired result.
> Fix unsupported platform on GenuineIntel

- recipes/FreeCAD-nightly.yml
+ Enable Matplotlib package
+ Additional python-tk package for Animation workbench
In last attempt i was too quick and didn't realize matplotlib package is already included but not used in AppImage. Proposed changes in this PR should enable the matplotlib package to be used after.
Related:
https://github.com/AppImage/AppImages/pull/316
Edit: For correctness and to reduce any potential possible future confusion.  Additional python-tk package was added due to Animation and not Plot workbench depending on it. I edited the initial description.
https://forum.freecadweb.org/viewtopic.php?f=22&t=27013&p=217633#p217633
> Enable Matplotlib package

- recipes/Boostnote.yml
The script could't find the .deb url, corrected the bug
> Fix the boostnote recipe, wasn't able to fetch the URL of the .deb file 

- recipes/Firefox.yml
The icon name filename has changed from mozicon128 to default128 in 59.0.1
> Change icon name Firefox.yml

- excludelist
Those seem to cause major problems on systems with never versions of libfontconfig (such as Fedora, and recently Arch and their derivatives). As they're most likely not direct dependencies, not bundling them shouldn't break anything.
CC @probonopd
> No longer bundle libharfbuzz and libfreetype

- recipes/FreeCAD-nightly.yml
I was just about to create FreeCAD related PR. To remove FreeType from the FreeCAD recipe and have seen this:
https://github.com/AppImage/AppImages/pull/323
I can confirm we where affected by the mentioned issue too. In addition we use libfontconfig1-dev package as a workaround on PPA (for not having to create a symlink). I guess it is harmless if it is added to the AppImage. But as it doesn't do anything from the AppImage perspective. Likely best to remove it altogether.
https://forum.freecadweb.org/viewtopic.php?f=10&t=15525&start=190#p222348
> Exclude: libfontconfig1-dev

- recipes/FreeCAD-0.16.yml
- recipes/FreeCAD-Daily.yml
+ New FreeCAD-0.16 recipe
+ Replaced FreeCAD-nightly with FreeCAD-Daily recipe
+ Updated FreeCAD (stable) recipe
Reference:
https://forum.freecadweb.org/viewtopic.php?f=10&t=15525&p=230075#p230075
P.S. I noticed one issue. It looks like when the application icon name contains "-" and desktop integration is enabled. The icon won't be applied and instead an empty icon will be presented in for example Unity. FreeCAD AppImage should work as expected but in FreeCAD-0.16 and FreeCAD-Daily AppImage the launcher icon related issue can be observed.
> Update FreeCAD recipes

- recipes/FreeCAD-0.16.yml
- recipes/FreeCAD-Daily.yml
- recipes/FreeCAD.yml
We don't pack CalculiX in FreeCAD AppImage. Newer versions of CalculiX don't work with older version of libgomp1 provided by Trusty. AFAIK we don't use libgomp1 anywhere in FreeCAD ATM. Therefore the easiest fix for now is not to include libgomp1 in AppImage and let CalculiX use the system default version.
Reference:
https://forum.freecadweb.org/viewtopic.php?f=3&t=28519
> Exclude libgomp1

- recipes/Inkscape.yml
* The inkscape's dev channel has already been deprecated.
* [bug] fixed inkscape@0.92.3 missing python package
restore dist to trust.
> * use the newest inkscape@0.92.3 version on stable channel

- .gitignore
This commit adds `out/` to .gitignore. The directory is used for
storing AppImages by pkg2appimage execution. So, let's ignore the
files because we don't need to manage them.
> Add out directory to .gitignore

- excludelist
libnsl.so.1 is not part of glibc anymore as of Fedora 28.
Let's this to find out whether this causes any trouble. 
According to https://github.com/RPCS3/rpcs3/issues/5224#issuecomment-434930594 it should be fine. 
Will have to revert this in case it causes trouble
> Do not exclude libnsl.so.1

- recipes/Blender.yml
So I was looking into this repository because I thought it seemed interesting to have a means of converting archives / debs to appimages, but ran into a few problems with something I thought would be easy. (Blender)
Basically, blender.org currently uses redirection techniques for the download pages that makes it hard to parse for a direct link. Because of this, I decided to use a direct link to blender 2.8 for the time being. Ideally, this would actually link to the executable for 2.79 available on the [download page](https://www.blender.org/download/) but currently uses a link to the blender 2.8 beta from [this page](https://builder.blender.org/download/) instead. 
If anybody has the know-how of dealing with this type of download-redirection, that would be very useful and would like to …
> Added Preliminary Blender (2.8 Beta) Recipe.

- recipes/VSCode.yml
VSCode icon file name changed from `code.png` to `com.visualstudio.code.png`
> Updated VSCode icon file name

- excludelist
1ba9538 commented out libcrypt.so.1 because Fedora 30 no longer ships it with glibc.  However, a duplicate entry was not removed, causing some AppImages to still fail to start.
> Remove duplicate libcrypt.so.1 entry

- appdir-lint.sh
To fix:
```shell
find: warning: ‘-name’ matches against basenames only, but the given pattern contains a directory separator (‘/’), thus the expression will evaluate to false all the time.  Did you mean ‘-wholename’?
```
---
In `excludelist`, thoses lines where not properly sanitized:
```
libxcb-dri3.so.0 # https://github.com/AppImage/AppImages/issues/348
```
As a result for this line, `$FILE` was, in that order:
```
libxcb-dri3.so.0
#
https://github.com/AppImage/AppImages/issues/348
```
> Fix the blacklisted files retrieval

- recipes/FirefoxDeveloperEdition.yml
In Firefox 67, each new installation of firefox started being
registered in the ~/.mozilla/firefox/installs.ini file. Each
new installation also created a profile. Profiles store bookmarks
and other user related meta data which users come to expect during
their browsing experience.
These new profiles do not inherit any data from previous profiles.
They exist to support multiple installations of Firefox on the
same system. Installations are identified by hashing the
installation path.
Since AppImages are mounted at /tmp/.mount_XXXXXX, where 'X' are
replaced by some hashed values. This means that Firefox interprets
each new run of a Firefox AppImage to be a new installation,
creating a new profile and not carrying over any of the meta data
a user would expect in their day to day usage of …
> Fix FirefoxDeveloperEdition per installation profile creation

- functions.sh
I recently tried building some appimage (I didn't make a note on which image it was) and got an error message from `rm` trying to remove some file under `/lib64/` something. Tracking the problem back it was the `delete_blacklisted()` function which removes both a file/symlink and its `readlink` expansion without any checks for the latter.
Here is a minimal test case, `Test.yml`. `libc.so.6` is blacklisted by default in `excludelist` so I make use of it below. **DONT BUILD THIS UNDER ROOT!!**
```yaml
app: test
ingredients:
script:
- echo dev > VERSION
script:
- cat > test.desktop <<\EOF
- [Desktop Entry]
- Name=Test
- Exec=test
- Icon=test
- Type=Application
- Categories=Development;
- EOF
- touch test.png
- ln -s /lib/x86_64-linux-gnu/libc.so.6
```
Last lines from the build log:
```
+ rm …
```
> Limit delete_blacklisted() function to only delete files from inside the current dir

- recipes/Google_Chrome.yml
Remove product_logo_22.png copy step as it no longer exists in the chrome package
> product_logo_22.png doesn't exist

- pkg2appimage
`strings` is used in `functions.sh` for getting the glibc version. This PR just adds a check to make sure the command is available.
> Check that `strings` command exists

- recipes/intef-exe.yml
Working recipe for [eXeLearning](https://exelearning.net/en/) educational editor ( repository [iteexe](https://github.com/exelearning/iteexe) on Github). Since it is a Python 2.7 application, an AppImage is a way of using it in recent Linux distros while the maintainers finish the transition to Python 3 (see [issue 95](https://github.com/exelearning/iteexe/issues/95) on their repo).
> Adding intef-exe.yml for exelearning.net e-learning resources editor

- pkg2appimage
These can be useful in CIs pipelines that generate debian packages or
populate their own local repository.
Add specific handling for the file: scheme when APT is used to print
packages URIs.
fixes #420
> Enable pkg2appimage to handle local APT repositories

- pkg2appimage
fixes pkg2appimage fail when there are no local APT repositories which causes $FILES variable to be empty
> Check and skip empty local APT repositories

- pkg2appimage
Fix a typo in ``pkg2appimage`` shell script.
> fix pkg2appimage test ARCH environment variable

- dogfeeding.sh
- functions.sh
- pkg2appimage
Now with support local .deb files
* [prebuild AppImage](https://github.com/sudo-give-me-coffee/pkg2appimage/releases/download/no-apt-experimental-build/pkg2appimage-x86_64.AppImage)
Tested recipes:
* Scribus
* Leafpad
* Firefox
* Spotify
> Bash-only APT replacement

- pkg2appimage
Refactor dependencies check (DRY) + add curl as seen in https://github.com/AppImage/pkg2appimage/pull/428
[L57](https://github.com/SwagDevOps/pkg2appimage/blob/check_dependencies_refactor/pkg2appimage#L57) COULD BE written on a single line (as YOU prefer), but I think it's better for version-control to split it on several lines.
> Check dependencies refactor

- pkg2appimage
Only the first package in `ingredients - packages` is bundled due to a syntax error in the script.
> Fix the extra dependencies is incomplete

- pkg2appimage
Sorry I forget that the double quotes also need to be removed, or bash will parse INSTALL as a single variable...
> Fix syntax

- pkg2appimage
I found that the ppa should be placed ahead of ubuntu's sources, or the newer version in ppa will not be download.
> Fix the package in PPAs not downloaded

- recipes/Viber.yml
- Viber dependency added which are not mentioned in viber itself related to `xcb`
- Used `stretch` as base rather than `jessie` which is now end of life.
This is for [issue 453](https://github.com/AppImage/pkg2appimage/issues/453)
> Viber dependency issue and base debian upgrade which resolves

- functions.sh
Currently there's kind of an inconsistency on how pkg2appimage's apt replacement handles slashes. It adds a slash when downloading the Packages.gz file, but not when downloading DEBs themselves (which requires the recipe to have a URL ending in a slash).
This means, if the source URL is `archive.ubuntu.com/ubuntu`, it will download `archive.ubuntu.com/ubuntu/dists/xenial/main/Packages.gz` (OK), but then downloads `archive.ubuntu.com/ubuntupool/[...]/pkg.deb` (gets 404).
If the source URL is `archive.ubuntu.com/ubuntu/`, it will download `archive.ubuntu.com/ubuntu//dists/xenial/main/Packages.gz`, and downloads `archive.ubuntu.com/ubuntu/pool/[...]/pkg.deb` (OK).
This is not an issue with first-party Ubuntu and Debian repos/PPAs, which ignore double slashes, but causes issues for …
> Make apt-get.update add an extra slash so the recipe doesn't have to

- recipes/FactorioDemo.yml
Version 1.0.0 (http://download.sourceforge.net/pg4l/Factorio_(demo)-1.0.0.glibc2.18-x86_64.AppImage) was tested successfully on these distros:
- ubuntu-14.04.6-desktop-amd64.iso
- ubuntu-16.04.7-desktop-amd64.iso
- Fedora-Workstation-Live-x86_64-33-1.2.iso
Version 1.1.30 (http://download.sourceforge.net/pg4l/Factorio_(demo)-1.1.30.glibc2.18-x86_64.AppImage) was only tested on Linux Mint 19.1 because it doesn't work on my hardware, it's no longer compatible with my graphics card
> Added Factorio (demo) recipe

- recipes/VSCode.yml
The old url is no longer working and has been replaced.
> VSCode: update url to update.code.visualstudio.com

- pkg2appimage
The command already prints the URL, in the current mode the generated log has so much noise that it makes no sense to use it for debugging
> Disable set -x when downloading package

- pkg2appimage
This PR is allowing an AppImage to be updateable by:
- adding the recipe's property `updateinformation`
- and passing it to the right function
It's fixing #479.
> Make updateable image

- recipes/KiCad-nightly.yml
Couple of things changed since the old recipe was created:
- js-reynauds personal repo is deprecated and there now exists an official development repo
- KiCad now needs boost >=1.59, so it's not compatible with neither trusty nor xenial
- There's now a dedicated kicad-nightly package. The app name had to be changed in order for the binary and .destkop auto-detect to properly work
Let me know if I did something stupid. This is my first appimage recipe after all ;)
> Update kicad nightly recipe to new repo

- recipes/Zoom.yml
Hello,
Translation does not work on Zoom.AppImage.
For the `usr/bin/zoom` file the translation folder is in `../zoom/translations/` while they are in `./translations/`.
To fix the problem I suggest replacing `../zoom/translations/` by `././././translations/` in the file `usr/bin/zoom`.
> Update Zoom.yml - Translations

- excludelist
As libglib isn't excluded anymore, we need to fully allow libgobject in appimages as well.
Remove previous libgobject exclusion from the excludelist.
> Do not exclude libgobject

- functions.sh
Invocation from docker was failing because the `generate_type2_appimage` function was attempting to operate on a local path `appimagetool` instead of expanding the `$appimagetool` variable, giving this error:
```
mv: cannot stat 'appimagetool': No such file or directory
```
Adding this line to my script fixed my job:
```sh
sed -i -e 's/mv appimagetool/mv $appimagetool/' /opt/pkg2appimage.AppDir/usr/share/pkg2appimage/functions.sh
```
Full CI script: https://gitlab.com/cajomar/snowballz/-/blob/59fc8c35168a007a064e63885425a47278bbb989/.gitlab-ci.yml
> Fix appimagetool usage in docker

- functions.sh
Took me a while to find this, but according to the pkg2appimage documentation, Debian repositories from the opensuse build system should be listed as:
dist: [ubuntu distrib]
sources:
- deb https://download.opensuse.org/repositories/[...]:/[software name]/[ubuntu distrib]/ /
...but in functions.sh, the parsing method employed in apt-get.update() is only compatible with the classical syntax such as 
- deb http://archive.ubuntu.com/ubuntu/ [ubuntu distrib] main universe
...so it fails and doesn't fill the Packages.gz file.
The present patch solves this (probably not very elegantly).
> Fixed correct handling of OBS repositories as debian source

- .github/workflows/build.yml
- excludelist
This Pull Request removes `libthai.so.0` from the excludelist. The original reason why `libthai` has been added to it is an issue that occurs when `libpango` is not bundled but `libthai` is (see #538). But since then, `libpango` has been removed from the excludelist in 2022. This means that the original reason why `libthai` has been excluded is no longer relevant. Therefore it can be removed from the excludelist. This fixes #538.
Additionally, this improves the excludelist formatting. There have been different places scattered across the excludelist in which libraries have been excluded or not excluded due to other libraries (like `libthai` / `libpango`). This brings them all (with all information and reasoning) in one block to prevent issues like this in the future. Additionally, it adds …
> Remove libthai from the excludelist and improve excludelist formatting

- excludelist
[Info from this recent issue at linuxdeploy](https://github.com/linuxdeploy/linuxdeploy/issues/292)
> add `libpipewire-0.3.so.0` to excludelist

- excludelist
I have noticed that my Qt6 AppImage is failing on new distros such as Fedora 40, Arch etc. 
It turns out an EGL/GLX integration is running into some issues, upon further inspection I found out about this issue here https://gitlab.freedesktop.org/mesa/mesa/-/issues/11316 
After removing libwayland-client.so.0 from AppImage all issues were suddenly resolved
> Add libwayland-client.so.0 to exclude list
