recipes/subsurface.sh
=> For probono

.travis.yml, recipes/subsurface.sh
Verified to work using https://gist.github.com/probonopd/71f86c865723353b77bf/7a75fd93ef2dd4c3c4fc7faaf8e8b101a4c98ff3
=> Support building 32-bit AppImage on 64-bit host

recipes/subsurface.centos6.sh
We build that from source, anyway.
Signed-off-by: Dirk Hohndel <dirk@hohndel.org>
=> Don't install libgit2-devel

README.md, bintray.sh
Moved to this repo all the changes to bintray.sh pushed to https://github.com/probonopd/AppImageKit/pull/112
It seems to [build fine](https://travis-ci.org/RazZziel/AppImages/builds/115538358) and [upload fine](https://bintray.com/raziel/generic/Leafpad/view#files)
=> Several improvements to bintray.sh, copied from AppImageKit

bintray.sh
Related to https://github.com/probonopd/AppImageKit/pull/112#issuecomment-196542987
=> Accept underscores separating application name from package version

recipes/engauge-digitizer/Dockerfile, recipes/engauge-digitizer/Recipe
@probonopd Please review. Docker file edited for local build and needs to be changed to server build.
Currently only main executable is copied to image, without license file and samples/docs. It will be added afterwards.
=> Initial build files for engauge-digitizer.

recipes/vlc/Recipe-3
@probonopd Please review this. Resulting appimage has some issues with finding libraries.
=> WIP: Add new Recipe for VLC

functions.sh
Shall we consider this case as well?
=> Extend move_lib with lib64 case

recipes/octave/Dockerfile, recipes/octave/Recipe
Tested on Centos6
Currently fails with ```octave: failed to exec '/usr/libexec/octave/4.0.3/exec/x86_64-pc-linux-gnu/octave-gui'``` message.
@probonopd to the rescue!
=> WIP: Create recipe for Octave

bintray.sh
This fixes almost all issues with `bintray.sh` reported by `shellcheck`, and makes https://github.com/probonopd/AppImageKit/pull/247 pass, when previously it failed in https://travis-ci.org/probonopd/AppImageKit/jobs/165409992
=> Fix or improve bintray syntax

recipes/meta/Atom.yml
The only thing wrong should be the icon.
In the .desktop file it creates, the icon points to:
Icon=/tmp/.mount_PuIRfy/.DirIcon
instead of .cache/thumbnails/...
=> Add Atom yml

recipes/meta/GitKraken.yml
I get the icon from the website. Not the best idea but it works
=> Add GitKraken.yml

recipes/meta/XnViewMP.yml
Upstream now provides an AppImage (http://newsgroup.xnview.com/viewtopic.php?f=82&t=34581) and this is proprietary software, so I don't know if you want to add this or not.
=> Add XnView MP

functions.sh
This is working correctly for me. I've checked a few packages:
```
-rwxr-xr-x 1 djcj djcj 83M Feb 12 10:51 ../out/Atom-v1.14.1.glibc2.14-x86_64.AppImage
-rwxr-xr-x 1 djcj djcj 58M Feb 12 10:48 ../out/Firefox-51.0.1.glibc2.3.3-x86_64.AppImage
-rwxr-xr-x 1 djcj djcj 90M Feb 12 10:36 ../out/GIMP-2.9.5.glibc2.17-x86_64.AppImage
-rwxr-xr-x 1 djcj djcj 67M Feb 12 10:57 ../out/Inkscape-0.92.0+66.silhouette1.19.glibc2.15-x86_64.AppImage
-rwxr-xr-x 1 djcj djcj 23M Feb 12 11:12 ../out/Synergy-1.8.8.rc1.fc3cc78.glibc2.15-x86_64.AppImage
-rwxr-xr-x 1 djcj djcj 25M Feb 12 10:54 ../out/XChat_IRC-2.8.8.glibc2.8-x86_64.AppImage
-rwxr-xr-x 1 djcj djcj 54M Feb 12 11:09 ../out/XnView_MP-0.84.glibc2.14-x86_64.AppImage
```
=> another try to prefer readelf over strings

functions.sh
This is required for reproducable builds (aka builds without network access) as
it happens in build.opensuse.org instances.
=> Allow to use static files instead of downloading them.

recipes/meta/CAMotics.yml
This PR adds a meta recipe for CAMotics, an open-source software which simulates 3-axis CNC machining.
=> Add recipe for CAMotics

recipes/meta/Toxic.yml
Toxic is a TUI client for the Tox project.
=> Add recipe for Toxic

functions.sh, recipes/meta/Recipe
Reverts probonopd/AppImages#201 since it breaks the build: https://travis-ci.org/probonopd/AppImages/builds/213125491#L1515
=> Revert "More improvements"

recipes/meta/FirefoxDeveloperEdition.yml, recipes/meta/Waterfox.yml
This PR adds two recipes:
* Firefox Developer Edition
* Waterfox (see https://github.com/MrAlex94/Waterfox/issues/127)
=> More Firefox related AppImage

recipes/meta/RedEclipse.yml
Just another example how to build an AppImage from Debian packages.
=> Recipe for Red Eclipse

recipes/meta/Recipe
After #201 has been reverted completely (only 1 of 4 commits caused builds to fail), I want to merge the 3 working ones separately with this PR.
=> Improve package downloading

functions.sh
Successor of the commit that was included in #201, but caused builds to fail.
=> Include glibc version in AppImage filenames

recipes/meta/GoldenCheetah.yml
Added the GoldenCheetah deb.
Not fully tested, but starts and seems to work properly for now.
=> Add GoldenCheetah

functions.sh
This PR fixes a few bugs introduced with PR #218.
=> Fix glibc version related issues

recipes/vlc/Recipe
I have some issues with Docker and can't test it though. By the way convincing upstream from providing an AppImage might be a good idea.
=> Updates in vlc recipe

recipes/meta/FreeCAD-nightly.yml
I likely had created more .yml files when doing tests yesterday. As when creating the PR 273 on copy/paste operation it looks like one line was missing:
https://github.com/AppImage/AppImages/pull/273
This PR should therefore resolve the mentioned issue.
=> Add missing line for PR 273

recipes/meta/FreeCAD-nightly.yml
PPA freecad-daily.desktop file should now pass validation. Temporary fix therefore is not needed anymore.
https://forum.freecadweb.org/viewtopic.php?f=4&t=24242&start=10#p191671
=> Revert .desktop temporary fix

pkg2appimage
Added a _"deb:"_ section and **disabled download of translation packages** for build AppImages more **easily** and **fast** by non programmers, i think that it's will be helpful
=> Added a "deb:" section

YML.md
Add documentation for https://github.com/AppImage/AppImages/pull/306
=> Add: DEB Section

pkg2appimage
Parse yml indented with tabs or spaces
=> Fix for Issue #308

recipes/Postman.yml
Add [Postman](https://www.getpostman.com/) Rest Client Recipe
=> Add postman recipe

recipes/Opera.yml, recipes/opera.yml
Added opera recipe, tested the compiled Opera AppImage on two PC and it works.
However, the deb URL for wget is fixed. I need help on the 'wget' line, how to let the terminal command automatically check for the latest version number before deciding to download the deb package.
I am a typical Linux GUI user, no terminal expert, so I have no idea on this. If any help to do on that line is much appreciated. :)
=> Opera recipe added

recipes/Signal.yml
First time creating a recipe, so there could very well be a few things missing.
=> Add signal-desktop recipe

recipes/IntelliJ-IDEA-Community.yml, recipes/PhpStorm.yml, recipes/PyCharm-Community.yml, recipes/PyCharm-Edu.yml, recipes/PyCharm-Professional.yml, recipes/Rider.yml
If you're OK with this template, I can add the other remaining apps made by them.
=> Add a couple of JetBrains IDEs

appdir-lint.sh
=> Check if .DirIcon is png (mimetype)

recipes/Blender.yml
Fixed my previous recipe for blender 2.8 since the download page was changed.
=> Fix URL Fetch for Blender 2.8 Recipe

recipes/gbgoffice.yml
A recipe for http://gbgoffice.info/ - an offline English-Bulgarian dictionary.
=> Create AppImage for gbgoffice with dictionaries

functions.sh, pkg2appimage
This commit  creates a very basic implementation of APT using Shell Script they:
- Downloads packages index
- Found requested packages
- Downloads dependencies recursively based on package dependencies
=> Fixes #404

recipes/Chromium.yml
Thought this might be useful for someone.
=> add Chromium.yml

recipes/cmus.yml
cmus — C* Music Player -- https://github.com/cmus/cmus
A successfull .yml recipe builded from debian buster.
=> Adding cmus.yml - a cli music player

recipes/Authy.yml
I created this because the snap package for Authy doesn't work on my system (due to AppArmor shenanigans), and I hate how long it takes to launch.
I hope this AppImage recipe can be useful to someone!
I managed to get the launcher icon working, but the app window icon does not show no matter what I try. Otherwise the recipe seems to work fine.
=> Add Authy.yml recipe

recipes/Anydesk.yml
Use anydesk deb repository
Update distribution to focal
=> Use anydesk deb repository

recipes/Postman.yml
StartupWMClass is required for ability to add AppImage as favorite
=> Missing StartupWMClass

recipes/wps-office.yml
Tested on Debian testing & SparkyLinux 7
=> Update wps-office link

recipes/Firefox.yml
The current recipes try remove a not existing file (blocklist.xml) and fails, commenting the line solves
=> Fix Firefox not building

recipes/VSCode.yml
Hello, the VScode recipe has changed,
#551
Best regards.
=> VScode.yml recipe update

recipes/neovim.yml
(cherry picked from commit b6435479f1cec9aaa3f6798f3e9ce4842f76bd8f)
=> Add neovim.yaml recipe
